INSERT INTO categories(name)
VALUES
('ÁO POLO THUN THỂ THAO'),
('ÁO THUN CAO CẤP'),
('ÁO THUN LẠNH CAO CẤP'),
('POLO COTTON CÁ SẤU 35773'),
('POLO COTTON CÁ SẤU'),
('ÁO THUN STRIPED 35820'),
('POLO WAFFLE COTTON CÁ SẤU'),
('QUẦN KAKI DÀI 35818'),
('QUẦN SHORT KAKI 35822'),
('QUẦN SHORT THỂ THAO')