INSERT INTO product(name,price,quantity,image,date,id_categories,status)
VALUES
('ÁO POLO THUN THỂ THAO - CAM', 489000.0, 1, 'ÁO POLO THUN THỂ THAO - CAM.jpg', CURRENT_DATE, 1, TRUE),
('ÁO POLO THUN THỂ THAO - TRẮNG', 489000.0, 1, 'ÁO POLO THUN THỂ THAO - TRẮNG.jpg', CURRENT_DATE, 1, FALSE),
('ÁO POLO THUN THỂ THAO - XÁM', 489000.0, 1, 'ÁO POLO THUN THỂ THAO - XÁM.jpg', CURRENT_DATE, 1, TRUE),
('ÁO POLO THUN THỂ THAO - XANH DENIM', 489000.0, 1, 'ÁO POLO THUN THỂ THAO - XANH DENIM.jpg', CURRENT_DATE, 1, TRUE),
('ÁO POLO THUN THỂ THAO - XANH LÁ', 489000.0, 1, 'ÁO POLO THUN THỂ THAO - XANH LÁ.jpg', CURRENT_DATE, 1, TRUE),
('ÁO POLO THUN THỂ THAO - XANH NAVI', 489000.0, 1, 'ÁO POLO THUN THỂ THAO - XANH NAVI.jpg', CURRENT_DATE, 1, TRUE),
('ÁO THUN CAO CẤP - TRẮNG', 329000.0, 1, 'ÁO THUN CAO CẤP - TRẮNG.jpg', CURRENT_DATE, 2, FALSE),
('ÁO THUN LẠNH CAO CẤP - HỒNG', 369000.0, 1, 'ÁO THUN LẠNH CAO CẤP - HỒNG.jpg', CURRENT_DATE, 3, TRUE),
('ÁO THUN LẠNH CAO CẤP - TRẮNG', 369000.0, 1, 'ÁO THUN LẠNH CAO CẤP - TRẮNG.jpg', CURRENT_DATE, 3, TRUE),
('POLO COTTON CÁ SẤU 35773 - BÈ', 489000.0, 1, 'POLO COTTON CÁ SẤU 35773 - BÈ.jpg', CURRENT_DATE, 4, FALSE),
('POLO COTTON CÁ SẤU - KEM ĐẬM', 489000.0, 1, 'POLO COTTON CÁ SẤU - KEM ĐẬM.jpg', CURRENT_DATE, 5, TRUE),
('ÁO THUN STRIPED 35820 - ĐỎ', 389000.0, 1, 'ÁO THUN STRIPED 35820 - ĐỎ.jpg', CURRENT_DATE, 6, TRUE)

DELETE FROM product